# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'missing_maps.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MissingMapsDialog(object):
    def setupUi(self, MissingMapsDialog):
        MissingMapsDialog.setObjectName("MissingMapsDialog")
        MissingMapsDialog.resize(865, 434)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/oce.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MissingMapsDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(MissingMapsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.container = QtWidgets.QVBoxLayout()
        self.container.setObjectName("container")
        self.api_box = QtWidgets.QGroupBox(MissingMapsDialog)
        self.api_box.setObjectName("api_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.api_box)
        self.verticalLayout_4.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.api_table = QtWidgets.QTableWidget(self.api_box)
        self.api_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.api_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.api_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.api_table.setRowCount(0)
        self.api_table.setColumnCount(6)
        self.api_table.setObjectName("api_table")
        item = QtWidgets.QTableWidgetItem()
        self.api_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.api_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.api_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.api_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/osu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.api_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/bloodcat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.api_table.setHorizontalHeaderItem(5, item)
        self.api_table.horizontalHeader().setVisible(True)
        self.api_table.horizontalHeader().setCascadingSectionResizes(False)
        self.api_table.horizontalHeader().setDefaultSectionSize(160)
        self.api_table.horizontalHeader().setSortIndicatorShown(False)
        self.api_table.horizontalHeader().setStretchLastSection(True)
        self.api_table.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.api_table)
        self.container.addWidget(self.api_box)
        self.unmatched_box = QtWidgets.QGroupBox(MissingMapsDialog)
        self.unmatched_box.setObjectName("unmatched_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.unmatched_box)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.unmatched_textbox = QtWidgets.QTextEdit(self.unmatched_box)
        self.unmatched_textbox.setReadOnly(True)
        self.unmatched_textbox.setObjectName("unmatched_textbox")
        self.verticalLayout_3.addWidget(self.unmatched_textbox)
        self.container.addWidget(self.unmatched_box)
        self.no_missing_label = QtWidgets.QLabel(MissingMapsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.no_missing_label.sizePolicy().hasHeightForWidth())
        self.no_missing_label.setSizePolicy(sizePolicy)
        self.no_missing_label.setAlignment(QtCore.Qt.AlignCenter)
        self.no_missing_label.setObjectName("no_missing_label")
        self.container.addWidget(self.no_missing_label)
        self.verticalLayout.addLayout(self.container)
        self.button_box = QtWidgets.QDialogButtonBox(MissingMapsDialog)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(MissingMapsDialog)
        self.button_box.accepted.connect(MissingMapsDialog.accept)
        self.button_box.rejected.connect(MissingMapsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(MissingMapsDialog)

    def retranslateUi(self, MissingMapsDialog):
        _translate = QtCore.QCoreApplication.translate
        MissingMapsDialog.setWindowTitle(_translate("MissingMapsDialog", "Missing Maps"))
        self.api_box.setTitle(_translate("MissingMapsDialog", "Missing maps identified with the osu! API"))
        item = self.api_table.horizontalHeaderItem(0)
        item.setText(_translate("MissingMapsDialog", "Artist"))
        item = self.api_table.horizontalHeaderItem(1)
        item.setText(_translate("MissingMapsDialog", "Title"))
        item = self.api_table.horizontalHeaderItem(2)
        item.setText(_translate("MissingMapsDialog", "Mapper"))
        item = self.api_table.horizontalHeaderItem(3)
        item.setText(_translate("MissingMapsDialog", "Difficulty"))
        item = self.api_table.horizontalHeaderItem(4)
        item.setToolTip(_translate("MissingMapsDialog", "Open this map\'s osu! page"))
        item = self.api_table.horizontalHeaderItem(5)
        item.setToolTip(_translate("MissingMapsDialog", "Search for this map on Bloodcat"))
        self.unmatched_box.setTitle(_translate("MissingMapsDialog", "Hashes of unidentified missing maps"))
        self.no_missing_label.setText(_translate("MissingMapsDialog", "You have no missing maps!"))

